### ISSUE TITLE
 Action client not connected: vs060/arm_controller/follow_joint_trajectory

### ISSUE THREAD

**Issue by ferraridamiano** [DENSORobot/denso_robot_ros#50]
Hi, I'm trying to connect ROS and MoveIt to the simulated vs060 inside Wincaps 3. I followed [your tutorial](http://wiki.ros.org/denso_robot_ros/Tutorials/How%20to%20control%20a%20simulation%20robot%20with%20MoveIt%21) but when I launch `roslaunch denso_robot_bringup vs060_bringup.launch sim:=false ip_address:=WINDOWS_PC_ADDRESS` I see in the standard output two errors:
```
...
[ERROR] [1655719837.693261276]: Invalid robot type.
...
[ERROR] [1655719854.571573812]: Action client not connected: vs060/arm_controller/follow_joint_trajectory
...
```
Here's everything I did:
1. Installed Ubuntu 18.04
2. Installed ROS Melodic
3. Installed `ros-melodic-denso-robot-ros`
4. Created a WinCaps 3 project with vs060 robot and started the simulation on the Windows PC
5. Started the service on bcapconfig
6. launched the command above

Obviously if I try to move the robot in Rviz and click plan and execute I got more error messages:
```
[ERROR] [1655720657.389995057]: Unable to identify any set of controllers that can actuate the specified joints: [ joint_1 joint_2 joint_3 joint_4 joint_5 joint_6 ]
[ERROR] [1655720657.390058348]: Known controllers and their joints:

[ERROR] [1655720657.390088555]: Apparently trajectory initialization failed
```

I can confirm that the packets between Ubuntu and Windows are exchanged (checked with Wireshark)

What should I do? Thank you in advance

**Comment by furukawahiromi** [comment]
Thank you for trying the denso_robot_ros package.
denso_robot_descriptions/vs060_description supports standard VS060. When creating a project with WinCAPS, Robot Model No. depends on the options.

It is recommended to generate the URDF with [ROSConverter](http://wiki.ros.org/denso_robot_ros/ROSConverter).
If you want to fix it manually, change [robot_name in vs060.launch.xml](https://github.com/DENSORobot/denso_robot_ros/blob/master/denso_robot_descriptions/vs060_description/vs060.launch.xml#L2) to your robot model no.

cf. Coding Information of Robot Model https://www.fa-manuals.denso-wave.com/en/usermanuals/000017/
